import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h2 className='text-2xl mt-10'>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum, eum.
        </h2>
        <h3>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
          reiciendis iste illo dolores eaque architecto? Quia expedita odio
          obcaecati tenetur!
          <button onClick={() => auth.signOut()}>Sign out</button>
        </h3>
      </main>
    </div>
  )
}
